### ISSUE TITLE
Where photos are being saved?

### ISSUE THREAD

**Issue by adnanmuttaleb** [expo/camerja#12]
after saving the photos in App.js:
```
 FileSystem.moveAsync({
          from: data.uri,
          to: `${FileSystem.documentDirectory}photos/Photo_${this.state.photoId}.jpg`,
        })
```

I could not locate them on my phone, I had checked the target path (${FileSystem.documentDirectory}photos/Photo_${this.state.photoId}.jpg`), but it does not exist.!!
In the GalleryScreen module the photos are being loaded from the state, so is the state persistent?

best regards

**Comment by jedau** [comment]
I'm not sure if you solved this, but the workaround I did was to use the `CameraRoll` instead.
