### ISSUE TITLE
Fail to connect to camera service

### ISSUE THREAD

**Issue by fadeltd** [expo/camerja#2]
When I try to press back from gallery, I can't go back and reopen camera

```
  renderGallery() {
    return <GalleryScreen onPress={this.toggleView.bind(this)} />;
  }
```

![21585757_10214694652625619_611448392_o](https://user-images.githubusercontent.com/4526413/30261884-cb3de7dc-96f8-11e7-830e-3bdde2bccbce.jpg)

**Comment by stevenmahana** [comment]
I am receiving the same error. 
[HERE](https://forums.expo.io/t/camera-unable-to-take-2nd-picture-fail-to-connect-to-camera-service-error/3886) is a post I added to the forum.

Has anyone found the cause of this error or found a work around? Resetting the stack (navigation) does not help in my case.

**Comment by willwlwang** [comment]
Please go vote for this feature request https://expo.canny.io/feature-requests/p/explicit-openclose-methods-for-camera
