### ISSUE TITLE
Base64 Boolean doesn't affect what's returned from takePictureAsync

### ISSUE THREAD

**Issue by jswhisperer** [expo/camerja#3]
https://docs.expo.io/versions/latest/sdk/camera.html#base64-boolean--whether-to-also-include-the-image-data-in-base64-format

setting the boolean to true, still only returns the url to the internal jpg

**Comment by jswhisperer** [comment]
I did a lot of digging, the only thing I could find was `node_modules/react-native/Libraries/Utilities/binaryToBase64.js` I see Expo points to React-Native for the CameraManager

**Comment by WebMobi59** [comment]
same here.
I am not sure how can I get image data from takePictureAsync() function.
`Object {
   "height": 1920,
   "uri": "file:///var/mobile/Containers/Data/Application/4E5695E9-31C1-4862-8787-9251DFCF44B6/Library/Caches/ExponentExperienceData/%2540anonymous%252Ftest-c92b9374-1193-4655-a4fd-82b0bc231227/Camera/7C22A977-63E5-43EF-9B94-DB10D8828513.jpg",
   "width": 1080,
 }
`

this is what I get when I log.

@gregbenner did you find solution?

**Comment by jswhisperer** [comment]
It seems to be working in the updated expo, try a fresh create-react-native-app project, with expo v.21
```
takePicture = async () => {
const newPicture = await this.camera.takePictureAsync({ base64: true })
console.log(newPicture)
```

**Comment by tmswartz12** [comment]
Hey. I am having this issue as well!
